### ISSUE TITLE
Lab is Unclear

### ISSUE THREAD

**Issue by davidjkim810** [learn-co-curriculum/react-props-and-state-lab#22]
This lab is very unclear doesn't provide guidance. 

1. The solution provided shows functional components as opposed to class components and there is no explanation in the teaching for this.
2. Pets gets passed a prop isAdopted and someone we're supposed to assume and know that this prop is to be a part of the pet array.
3. Neat lab with great concepts but no consideration to guide or help students.

**Comment by maxwellbenton** [comment]
Hi @davidjkim810,

Thank you for providing this feedback. We've updated the solution to display class based components, added a message in the readme regarding the isAdopted prop, and believe this issue is resolved.

Thank you for ensuring future students have an improved experience with this content!
