### ISSUE TITLE
Tests are not compatible with async/await syntax

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/react-props-and-state-lab#25]
Tests give `ReferenceError: regeneratorRuntime is not defined` if async/await is used, but pass if promises are used in `onFindPetsClick` tests

**Comment by maxwellbenton** [comment]
Hey @micahshute,

They do now! Turns out the React async labs just needed `babel/polyfill`. Adding in polyfill allows for both Promise based and async/await based solutions to pass the tests, which should resolve this issue.

I've also applied this change to the other [fetch lab](https://github.com/learn-co-curriculum/react-async-fetch-lab). Thanks for spotting this!
